image_width: 1280
image_height: 720
camera_name: "Realsense Camera (Camera)"
near_clip: 0.1      # remove this
far_clip: 5         # remove this
camera_matrix:
  rows: 3
  cols: 3
  data: [468.456, 0, 320, 0, 468.456, 240, 0, 0, 1]
distortion_model: "plumb_bob"
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0, 0, 0, 0, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [468.456, 0, 320, 0, 0, 468.456, 240, 0, 0, 0, 1, 0]
